### ISSUE TITLE
jaysonsantos && nickl-

### ISSUE THREAD

**Issue by nickl-** [Aeronautics/aero#1]
Hi!

I've been doing some work on Respect/Foundation and @alganet suggested I have a look at this project too. Please create some issue if there are any features you want or points that you think we should be looking at. 

Consider this project entering active development so expect progress. Now is the perfect time to get involved and everyone is welcome.

**Comment by jaysonsantos** [comment]
We are in a dilemma, should we use bash or python? Both are standard in almost any *nix, but python is a cleaner way to do stuff.
What do you think?

**Comment by nickl-** [comment]
@jaysonsantos I liked what I saw here originally, not being your std run of the mill scripts and I like that you take a clean implementation into consideration. I must be honest my python foo is very much under developed  which certainly does not mean that Im not keen to put in some quality time with her or that I'm not up for the challenge but these should not be factored into our decision. Ultimately it should consider what's best for the project and in the same instance it is important that there is a community so who will be using this and what are they mostly working with?

That said, I don't think I am 100 % clear on what we are trying to accomplish either. If you don't mind please write a few lines about the mission, where the idea came from some history perhaps and then mostly where you want us to take this. What are your thoughts?

**Comment by alganet** [comment]
The idea came when I attended a talk from @zenorocha. He did a live coding session about CSS and pre-processors, and he was using a lot of different package managers to accomplish what he needed.

I commented with a fellow that using different package managers is a deep flaw on software development, and he argued saying most package managers share a similar interface. That fact was kept cooking on my mind for some days until I realized that is possible to abstract just the interface of those, not the entire dependency/distribution/packaging thing.

`aero search`, `aero install` `aero list` and `aero uninstall` should be enough for starting small. Awareness of global (brew, apt-get, pear) and local (npm, composer) package managers is also something that I believe we should consider.

Mac and Linux support should be easy on bash, Windows wouldn't be so straightforward, but Windows doesn't have a strong culture of package management and we can't please everyone).

I'm not fluent in either Python or Bash (and that's the main reason I haven't coded here yet, besides my permanent state of not enough time =P), I have no bias here.

**Comment by jaysonsantos** [comment]
Besides the history, we should try to get a clean way to write those stuff.
If you check the branch python, you will see that is more easy to understand than bash (which is kind strange to do stuff).
I vote for python, but i'm alone cannot make that decision.

**Comment by nickl-** [comment]
O no you don't! You guys are not going to put it on me to decide besides if it is to be a decision made through voting then we need to set up a poll somewhere and get the hordes to vote it holds very little value between the 3 of us.

I vote we weigh up the pros and cons and then let the data reveal our course of action. You bring your arguments to the table and we support the arguments we agree with. This makes more sense than voting, would you agree?

Edit: Some facts before I start to go on (this being an edit after the fact) anyway. The project is about package managers so the target environment is the shell/terminal and where ever a package manager is used. 
As @alganet suggests we are focusing on `aero search`, `aero install` `aero list` and `aero uninstall` may I suggest that we add `aero update` and `aero self-update` to the mix specifically at this early stage as I'm having the feeling this might impact many of our design decisions. 

My honest feelings: I didn't see the python branch before but as I browsed through the code I couldn't help but think why not PHP CLI then? We have ample skills, @henriquemoody for one would be keen to get involved on a CLI project, we need more components in PHP which we've been discussing like ansi library and phar generation etc. So the effort we put in here is going to of greater benefit than just this project.

Looking at the github [language stats](https://github.com/languages) if that is anything to go by then we should write it in node. Here too we have more skills again it might be a strange choice unless we get out of the box, hmmmm and can you picture this aero boing airborn and it connects remotely to install. I can connect to you and install your environment directly while still utilizing my local package managers I just pull or push the list of instructions so to speak.=) Let me just drag myself back from that tangent

The difference between our other 3 options are marginal and the little I know about python I think those figures are based on a much larger spectrum than the shell or PHP themselves but I will agree on the facts PY is on top. Yet while I am looking through the python nothing jumps out WOW to me. As said before I have no problem learning python it's been on my to do list for a while. Which in itself should be alarming as I haven't been overly eager to leave all the funky stuff to get stuck in Python instead. I haven't had anything I needed python for that I couldn't do in something else. Which leads back to usability, I have nothing in the immediate horizen that would benefit from spending time in python now nor are there any other project I am involved with that can benefit from this. @jaysonsantos I don't want to get your enthusiasm down, this is exactly the point, we should all be excited, but you are going to have to bring a better motivation to the table than it's cleaner than bash. Please do I would hate to miss out on something I'm not aware of that would suck.

Then as truth be told when I opened up the bash again I couldn't restrain my smiles and there is an urge to dive in. Yes it's not pretty but yet it is =) Where else can you if fi and $? your $# to >&2 hehehe lots of documentation lots and lots and many more lots of variations and possibilities to leave no cat un-skinned. That said though looking at github languages stats again it is without a doubt which the most popular shell project is. I've been meaning to look at oh-my-zsh  at what would you have:

> Includes 40+ optional plugins (rails, git, OSX, hub, capistrano, brew, ant, macports, etc),

It seems they have already laid the ground work. We tap into a thriving community, while benefiting an active codebase which will make our efforts so much more rewarding. This already gives us an environment as stepping post to work of if they have done the leg work to enable all these package managers already which makes our task easier. That said I have not the slightest clue what zsh is but it does sound tempting and promising and at least, even if it just makes your shell experience a tad better then we are gaining something. Which we force ourselves to do now. I am sure my assumptions are right that @alganet knows just as little about zsh and if this just happens to be a grey area for yourself @jaysonsantos then I vote we all learn something new and we are in the same boat. Going through the same frustrations reaping the same rewards.

**Comment by nickl-** [comment]
### skills:

<table><tr>
<th><th>PHP<th>Node.js<th>Python<th>Bash<th>zsh
<tr>
<td>@alganet<td> 9 <td> 5 <td> 0 <td> 5 <td> 5
<tr>
<td>@nickl-<td> 9 <td> 6 <td> 0.25 <td> 8 <td> 8
<tr>
<td>@jaysonsantos <td>7 <td> 5 <td> 9 <td> 7 <td> 7
<tr>
<td>@henriquemoody <td>9 <td> 2 <td> 1 <td> 6.5 <td> 6.5
</tr></table>

Please fix these by just editing this issue, it's fine.

After some closer investigation zsh appears to be bash++ so skills will transfer I will get some references together.

**Comment by nickl-** [comment]
[Wikipedia - List of software package management systems](http://en.wikipedia.org/wiki/List_of_software_package_management_systems)

<table><tr>
<th>dpkg <th> APT <th> Homebrew <th> rudix <th> Fink <th> MacPorts
<tr>
<td>C, C++, Perl <td> C++ <td> Ruby <td> Python <td> Perl <td> Tcl, C
</tr></table>

**Comment by jaysonsantos** [comment]
I've changed my skills above.

There are two strong points that make python better to write it.
First is its learning curve which is ridiculous, i'ts very easy to learn.
Second, it is widely used both in mac and linux, the other languages will demand an effort from end user, the basic idea is to just install aero and start using.

**Comment by henriquemoody** [comment]
I have written something in bash, an sincerely I don't think that is a good idea to write aero in bash.
We will work with a multiple kinds of documents, like  XML and  JSON, and do parse of this kind of data even with libraries in bash always make me upset.
We know that PHP has what is necessary for create CLI applications, but its have a little of complications. We can talk about readline, ncurses, pcntl and other things that are great to create CLI scripts but are not core functionalities.
I like of Node.js, but Javascript sometimes make me upset, too.
I don't care to learn Python, contrariwise I will like. I think Python is our better option for many reasons, is installed by default on Linux and OSX, have a great integration with the OS and haves functionalities to create CLI scripts in its core. 
Btw, if we decide to use Python we probably will white this in Python 2, that is not the last version, I just don't like it, but is not a real problem.
I vote for Python, but @jaysonsantos have to guide me with what I don't know about programming in Python.

**Comment by nickl-** [comment]
That's a little misguiding don't you think? How is PHP and especially bash
less accessible?

I do not mind entertaining any valid arguments but they will have to
reflect or at least be supported by fact. Easy learning curve I am afraid
will also not get me all excited, it sounds to me what you are say is that
it is boring. =)

For someone to be involved and eager to work on an open source project,
well for me at least, you have to have a good lot of the WOW factor. Is
there anything from your suggested course of action that would facilitate
that?

**Comment by nickl-** [comment]
@henriquemoody glad to have you on board! =)

You shouldn't get upset with code though just take a deep breath and keep
trying it will come right eventually. Node.js unfortunately fails our
"pre-installed everywhere" rule set but that said, are we not writing a
package manager? Why are we concerned about what is installed or not when
we get there. We are in the business of installing what we want so lets
stick to our focus.

I could imagine we would have to be able to:
- detect which package managers are present,
- install additional package managers
- search, via installed manager for new packages
- verify via installed manager if package is installed
- update/delete package via package manager

I don't think we want to write a new package manager just a tool to
facilitate the combined usage of available PMs so if that is the case then
there won't be any json xml etc we will be working with I/O streams which
brings me back to the shell again.

**Comment by alganet** [comment]
Not only Python 2.x, but as @jaysonsantos said to me earlier, we need to code in Python 2.4, which is really old. Bash is old as well, we can't rely much on newer versions and specially on OS X tools like sed, tr and other GNU tools that aren't GNU on Mac. I just feel sad for package managers.

**Comment by nickl-** [comment]
I see I didn't make my point in the previous post :

> Why are we concerned about what is installed or not when
> we get there. We are in the business of installing what we want so lets
> stick to our focus.

We really have everything at our disposal to establish the environment we need. This is not additional work required we have to have this capability already. What better way to test then when we self update, self install, etc

If that is a consideration it might open some other possibilities.
- [fish](http://ridiculousfish.com/shell/)\- Finally, a command line shell for the 90s
  The new fish is a smart and user-friendly command line shell for OS X, Linux, and the rest of the family
- [ZMQ](http://zguide.zeromq.org/page:all) - Fixing the World
  The physics of software is not algorithms, data structures, languages and abstractions. These are just tools we make, use, throw away. The real physics of software is the physics of people.
- [Erlang](http://www.erlang.org/doc/man/shell.html) is a programming language
- [IPython](http://ipython.org/ipython-doc/stable/overview.html) Interactive Computing
  create a comprehensive environment for interactive and exploratory computing.
- [Tcl](http://wiki.tcl.tk/299#pagetoc9c9bb55e)  the "Tool Command Language"*,
  a simple, multiparadigm programming language
- [clig](http://wsd.iitb.fhg.de/~geg/clighome/) Command Line Interpreter Generator
  For the impatient and those who know
- [OCaml](http://caml.inria.fr/about/index.en.html)  Caml is a general-purpose programming language, 
  designed with program safety and reliability in mind. OCaml offers a richer programming language as well as efficient native code compilers for many architectures.
- [Haskell](http://hackage.haskell.org/platform/contents.html) Programming Language - this one is for @henriquemoody =) will learn patience here guaranteed 
  rapid development of robust, concise, correct software makes it easier to produce flexible, maintainable, high-quality software.

Why does it have to be a terminal app? I've been watching this project and hearing good things. It's like the long lost cross platform windowed solution we've always wanted just never got right. It's probably been a while but surely everyone can still remember how to say Pascal in some weird accent of sorts =)
- [freepascal](http://www.freepascal.org/) aka FPK Pascal 
  is a 32 and 64 bit professional Pascal compiler. It can target multiple processor architectures: Intel x86, AMD64/x86-64, PowerPC, PowerPC64, SPARC, and ARM. Supported operating systems include Linux, FreeBSD, Haiku, Mac OS X/iOS/Darwin, DOS, Win32, Win64, WinCE, OS/2, MorphOS, Nintendo GBA, Nintendo DS, and Nintendo Wii.

**Comment by nickl-** [comment]
You guys are just going all out to paint the python option bland aren't you @alganet ?

> we need to code in Python 2.4, which is really old.

Like really now? Learn something "new" and start with Noah and is Arch?!?!? 

@jaysonsantos and you haven't found anything else to add neither, still gunning for the more accessible than others and curves like a small breasted convent girl? Sheesh! 

At least lets pick up where 2.6 left off which is what [phpsh](/facebook/phpsh) is going on, I'd love to transfer some skill that way while we're at it then. If you consider they haven't done a singe commit in 2 to 3 years then you know it's ancient. 

From the horses mouth [python.org/getit](http://www.python.org/getit/) If you don't know which version to use, start with Python 2.7;surely they are doing semantic revisions, am I right? 

If we add the skills together though you can see where our strengths are. We don't need new dev environments configured. We get to grow the other libraries too that are in need of some cli. If software version is still an argument then we spend time learning hiphop and while we are toying with all the PMs under the sun we might as well get hiphop compiling on Mac OS X. 

More skill that can take us the distance and we can actually spend time making something WOW which ppl will recognize and appreciate rather than learning how to program 101. Looking at our combined skill ratings we stand just as good a chance writing this in [BrainFuck](http://en.wikipedia.org/wiki/Brainfuck) hehee

I'm not against the Python though... but the Pascal gets my vote for sure and I'd love to spend time on Erlang with something serious. Should we expand the skills grid again? I know you want to see BF on there ;)

**Comment by nickl-** [comment]
The [zsh guide](http://zsh.sourceforge.net/Guide/zshguide.html) I promised. You also know very well that we probably won't bother learning any of that if we don't just jump in head first. Plus @alganet is right? bash is from 77 hallo?

Do check out fish though I've been watching the project for a while and they are very actively working on it there. 

Ok I think I've done enough damage here, let me go spread some terror elsewhere.
