### ISSUE TITLE
PEP 8

### ISSUE THREAD

**Issue by jaysonsantos** [Aeronautics/aero#17]
All code should be more PEP8 compatible, we can just ignore E501, but the others are very useful.

**Comment by nickl-** [comment]
Can you elaborate with some references added perhaps, keep in mind python n00bs around. 

All I get is **What The?**

**Comment by nickl-** [comment]
PEP8  compliance with --max-line-length=120 @f5b93ab3a5e7960e57f695832d1d9c27bd4ab8a5
