### ISSUE TITLE
For development, use virtualenv to isolate your dependences and maybe python version

### ISSUE THREAD

**Issue by jaysonsantos** [Aeronautics/aero#19]
The basic idea is execute make bootstrap it setups your full development enviroment.

**Comment by jaysonsantos** [comment]
Fixed

**Comment by nickl-** [comment]
@jaysonsantos can you please elaborate on this or maybe provide some links, I am not sure what it entails even after spending the whole of yesterday with it. I already have 2.6 2.7 3.3 installed and can specify the appropriate versions thrraugh manipulating the include path priorities. 

In particular I am concerned about:
How is this approach different?
How will this effect my current configuration?

**Comment by jaysonsantos** [comment]
@nickl- Call me in PVT on irc and we can talk about this and abc module.

**Comment by nickl-** [comment]
We should still get around to this someday...
