### ISSUE TITLE
macports

### ISSUE THREAD

**Issue by nickl-** [Aeronautics/aero#5]
Not currently on the list of adapters/package managers but no reason why it shouldn't be, do you disagree?

It is not for us to dictate your preferences nor should we be concerned about the pros and cons of this or that PM, IMO
What are your thoughts on this, let us know?

This task needs to be completed as part of milestone Version 0.1 see #2

**Comment by alganet** [comment]
I believe even some bundled OS X open source applications that come with it should be considered. An `aero search` listing which shows Apache, PHP, Python, Ruby and their versions will be useful for describing a full environment (a task that our humble package recycler would do very well).

**Comment by nickl-** [comment]
Macports enabled with the following commands enabled:
- search
- install
- update
