### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by nickl-** [Aeronautics/aero#6]
No current implementation

Should we differentiate between local and global?

This task needs to be completed as part of milestone Version 0.1 see #2

**Comment by alganet** [comment]
We could search for a package.json file (including parent directories, just like Git does with it's folder). A switch for local/global (just like the npm's -g option) could be useful.

**Comment by nickl-** [comment]
Npm has been enabled with initial support for commands
- search
- update
- install 

I'm closing this issue we can raise new ones. 

global local could be addressed with pass through attributes perhaps
